version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
     - "8080:8080"
    volumes:
     - ./web:/app
    environment:
      ENV: local
      TWITTER_CONSUMER_KEY: $TWITTER_CONSUMER_KEY
      TWITTER_CONSUMER_SECRET: $TWITTER_CONSUMER_SECRET
      TWITTER_ACCESS_TOKEN: $TWITTER_ACCESS_TOKEN
      TWITTER_ACCESS_TOKEN_SECRET: $TWITTER_ACCESS_TOKEN_SECRET
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  front:
    build:
      context: .
      dockerfile: Dockerfile-front
    volumes:
      - ./front/src:/app/src
    ports:
      - 3000:3000
    command: npm run serve
